theme: jekyll-theme-modernist
title: Thank you for visiting my ePortfolio!
description: My name is Kelsey Stokes and this is some of the work I completed during my time at Southern New Hampshire University.

